# Generated by Django 5.0.2 on 2024-02-28 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
